name: Publish
run-name: Publish ${{ inputs.version }} (@${{ github.actor }})

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Install NPM Dependencies
        run: npm ci

      - name: Publish
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          npm version ${{ inputs.version }}
          npm publish
          git push
          git push --tags
